function add_sgtitle_compat(fig, titleStr)
% ADD_SGTITLE_COMPAT Add a figure-level title with a fallback for older MATLAB.

    if exist('sgtitle', 'file') == 2
        figure(fig); %#ok<LFIG>
        sgtitle(titleStr, 'Interpreter', 'none');
    else
        annotation(fig, 'textbox', [0.05 0.96 0.90 0.04], ...
            'String', titleStr, ...
            'EdgeColor', 'none', ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'Interpreter', 'none', ...
            'FontWeight', 'bold');
    end
end
